FROM arm64v8/ros:noetic

ENV DEBIAN_FRONTEND=noninteractive
RUN apt-get update && apt-get install -y tzdata
RUN ln -fs /usr/share/zoneinfo/Asia/Kolkata /etc/localtime
RUN dpkg-reconfigure --frontend noninteractive tzdata

RUN apt-get update && apt-get upgrade -y
RUN apt-get update \
   && apt-get -y install --no-install-recommends \
   software-properties-common git libusb-1.0-0-dev \
   wget zsh python3-catkin-tools v4l-utils

RUN apt-get install -y ros-noetic-pcl-ros  \
    ros-noetic-rtabmap-ros ros-noetic-rqt ros-noetic-rqt-image-view

RUN apt-get install -y \
    python3-dev \
    python3-pip \
    python3-catkin-tools \
    python3-osrf-pycommon \
    python3-rosdep 

RUN pip3 install rospkg pyyaml numpy opencv-python==4.5.4.60 \
    opencv-contrib-python==4.5.4.60 transforms3d pyquaternion \
    scipy matplotlib ipython jupyterlab

RUN echo "source /opt/ros/noetic/setup.bash" >> ~/.bashrc
RUN echo "source /ws/devel/setup.bash" >> ~/.bashrc
RUN echo "source /workspace/devel/setup.bash" >> ~/.bashrc
RUN echo 'export PS1="[NOETIC][DAI][\u@docker] \W # "' >> ~/.bashrc